services:
  ato-cfip:
    image: ghcr.io/clover-eric/ato-cfip:sha-bd872ef
    pull_policy: always
    container_name: ato-cfip
    restart: unless-stopped
    environment:
      ATO_CFIP_GITHUB_ACCELERATOR: "https://github.i3.pub"
    ports:
      - "33668:8080"
    volumes:
      - ato-cfip-data:/app/data

volumes:
  ato-cfip-data:
