services:
  ato-cfip:
    build:
      dockerfile_inline: |
        FROM scratch
        ARG TARGETARCH
        ADD https://github.com/clover-eric/ato-cfip/releases/latest/download/ato-cfip-linux-${TARGETARCH} /app/cfst-daemon
        ADD https://raw.githubusercontent.com/clover-eric/ato-cfip/main/config.example.yaml /app/config.yaml
        ADD https://raw.githubusercontent.com/clover-eric/ato-cfip/main/ip.txt /app/ip.txt
        ADD https://raw.githubusercontent.com/clover-eric/ato-cfip/main/ipv6.txt /app/ipv6.txt
        EXPOSE 8080
        ENTRYPOINT ["/app/cfst-daemon", "-config", "/app/config.yaml"]
    image: ato-cfip:standalone
    container_name: ato-cfip
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ato-cfip-data:/app/data

volumes:
  ato-cfip-data:

