FROM alpine:3.20

RUN apk add --no-cache ca-certificates tzdata
WORKDIR /app

COPY ato-cfip /app/cfst-daemon
COPY ip.txt /app/ip.txt
COPY ipv6.txt /app/ipv6.txt

VOLUME ["/data", "/config"]
EXPOSE 8080

CMD ["/app/cfst-daemon", "-config", "/config/config.yaml"]
