package publisher

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/clover-eric/ato-cfip/internal/model"
)

type FilePublisher struct {
	OutputFile string
	HostsFile  string
}

func (p FilePublisher) Publish(ctx context.Context, set model.PublishedSet) error {
	if p.OutputFile != "" {
		if err := writeJSON(p.OutputFile, set); err != nil {
			return err
		}
	}
	if p.HostsFile != "" {
		if err := writeHosts(p.HostsFile, set); err != nil {
			return err
		}
	}
	return nil
}

func writeJSON(path string, set model.PublishedSet) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	b, err := json.MarshalIndent(set, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(path, append(b, '\n'), 0o644)
}

func writeHosts(path string, set model.PublishedSet) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	var b strings.Builder
	b.WriteString("# generated by cfst-daemon\n")
	for _, ip := range set.IPs {
		b.WriteString(fmt.Sprintf("%s %s\n", ip.IP, set.Domain))
	}
	return os.WriteFile(path, []byte(b.String()), 0o644)
}
